controllers:
    resource: ../src/Controller/
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index

app_connexion_user:
    path: /connexion
    controller: App\Controller\ConnexionController::index

app_disconect_user:
    path: /disconnect
    controller: App\Controller\ConnexionController::disconect

app_inscription_user:
    path: /inscription
    controller: App\Controller\InscriptionController::inscription

app_all_games:
    path: /games/{platform}
    controller: App\Controller\GamesController::showGamesByPlatform

app_one_game:
    path: /games/{platform}/{id}
    controller: App\Controller\GamesController::showGameByPlatformAndId

app_delete_game:
    path: /games/{platform}/{id}
    controller: App\Controller\GamesController::deleteGame
